### ISSUE TITLE
Toepassingsgebied van de standaard beschrijven

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/Terugmelding#3]
### Omschrijving

"Met de terugmeldstandaard kan iedere registratie een eigen terugmelddienst opzetten" geeft aan dat de standaard bedoeld is voor breed gebruik binnen de overheid. Lees: hij moet bruikbaar zijn voor iedere bronregistratie. Op andere plaatsen lijkt het vooral om de basisregistraties te gaan: "begrippen die in het kader van stelselcatalogus worden gebruikt", attribuut "basisRegistratieCode" in voorbeeldbericht. 
Het moet duidelijker worden beschreven voor welke soorten registraties de standaard voor terugmeldingen is bedoeld. 

Mijn voorkeur gaat uit naar: "voor alle registraties binnen de overheid". 

### Naam

Ad Gerrits

### Email

ad.gerrits@vng.nl

### Organisatie

VNG

**Comment by adgerrits** [comment]
De mate van beoogd verplicht gebruik van de standaard en de doelgroep blijft wat onduidelijk. De laatste zin "Grote registraties kunnen zelf een API koppelvlak aanbieden en maken geen gebruik van een terugmelddienst" snap ik bijv. niet zo goed. Wordt daarmee bedoeld dat ze de standaard niet verplicht hoeven te (gaan) gebruiken?

**Comment by edwinwisse** [comment]
Daarmee willen we zeggen dat de standaard bedoeld is om geïmplementeerd te worden door grote registraties. Deze kunnen dus zelf een koppelvlak aanbieden op basis van de standaard. Kleinere registraties voor wie een eigen dienst niet nodig is kunnen gebruik maken van een terugmelddienst (zoals Digimelding) die daarvoor aangeboden wordt.

**Comment by edwinwisse** [comment]
In de aanvraag voor de pas-toe-of-leg-uit-lijst van het Forum staat nu als toepassings- en werkingsgebied van opname:
> Het uitwisselen van notificaties op wijzigingen in de basisregistraties en andere registraties binnen het Federatief Datastelsel.
