### ISSUE TITLE
Standaardiseren op een hoger abstractieniveau

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/Terugmelding#4]
### Omschrijving

Een standaard met een hoger abstractieniveau biedt partijen de mogelijkheid om implementatiekeuzes te maken die binnen hun context het meest geschikt zijn.  
Gebruik van REST-API's is een mogelijke implementatiekeuze. Gelet op de voorkeur daarvoor die er momenteel is binnen de overheid, kun je aanvullend op de standaard afspraken maken over gebruik van de standaard via REST-API's. 
Maar je kunt de standaard dan bijv. ook toepassen bij gebruik van asynchrone berichten (wat ik persoonlijk logischer vind voor terugmeldingen). 

### Naam

Ad Gerrits

### Email

ad.gerrits@vng.nl

### Organisatie

VNG

**Comment by edwinwisse** [comment]
De keuze voor een API of CloudEvents invulling kan nog gemaakt worden. Dat is een vraag voor een komend TO.

**Comment by edwinwisse** [comment]
We hebben nu een keuze gemaakt om terugmelden als REST API standaard uit te werken. ZIe ook [ontwerp terugmelding](https://github.com/Logius-standaarden/Terugmelding/tree/develop/Ontwerp). Punt 2:

> De standaard is gericht op implementatie in een REST API koppelvlak. Een WUS koppelvlak wordt als ingewikkeld en verouderd ervaren. Dit houdt breed gebruik tegen. Authenticatie is inmiddels goed mogelijk met API standaarden zoals OAuth waardoor de noodzaak voor gebruik van een WUS koppelvlak wegvalt. De API First strategie die overheidspartijen hebben omarmd is ook een reden te kiezen voor een API koppelvlak. De specificatie van de gegevens die uitgewisseld worden zijn gespecificeerd in JSON.

**Comment by adgerrits** [comment]
De tekst in het Ontwerp bij '[Vervolgstappen](https://github.com/Logius-standaarden/Terugmelding/blob/develop/Ontwerp/README.md#vervolgstappen)' moet dan nog aangepast worden neem ik aan.
Overigens kan CloudEvents ook prima toegepast worden bij gebruik van een REST API, dus ik kon het nog niet uit de tekst bij 2 concluderen. Maar het is nu helder. Goede beslissing vind ik.
