### ISSUE TITLE
Kiezen voor huidige objectgerichte of nieuwe gebeurtenisgerichte werkwijze i.r.t. CloudEvents

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/Terugmelding#5]
### Omschrijving

CloudEvents is een standaard om plaatsgevonden gebeurtenissen te beschrijven. Bij terugmelden werd en wordt een 'object-gerichte' stijl gebruikt, bedoeld om foutieve gegevens over objecten aan te passen. 
Wil je CloudEvents gebruiken waarvoor het is bedoeld dan moet je gebeurtenisgericht gaan terugmelden. Bijv. door aan de melderkant onderscheid te gaan maken in verschillende soorten gebeurtenissen zoals _bijvoorbeeld_ 'Foutief adres geconstateerd', 'Foutief persoonsgegeven geconstateerd','Nationaliteit betwijfeld'. De events die richting bronhouder gaan kun je dan gestandaardiseerd beschrijven met gebruik van CE/profiel. 
Dat biedt nieuwe mogelijkheden, zoals het abonneren op bepaalde type terugmeldingen (door bronhouder of een andere partij),  maar het wordt daardoor een hele andere werkwijze dan nu het geval is met het 1 op 1 uitwisselen van meldinggegevens in de vorm via REST-API's met 'resources'. 
Blijft het een object-gerichte uitwisseling, zoals de voorbeelden nu beschrijven, dan is het gebruik van CE/profiel misplaatst en is het alleen maar extra ballast. 

### Naam

Ad Gerrits

### Email

ad.gerrits@vng.nl

### Organisatie

VNG

**Comment by edwinwisse** [comment]
Dit gaat over dezelfde keuze API/CloudEvents die ook in #4 aan dr orde komt. Deze vraag wordt besproken in een komend TO.

**Comment by adgerrits** [comment]
De 2 voorbeelden met berichten waar CloudEvents wordt gebruikt geven nu een 404.

**Comment by sanderke** [comment]
In het Technisch Overleg Terugmelden van 6 juni 2024 is besloten te richten op een minimaal terugmeldbericht en daarmee het CloudEventsformaat uit het ontwerp te halen:
- #7
