### ISSUE TITLE
NL GOV profile for CloudEvents correct gebruiken in de voorbeelden

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/Terugmelding#6]
### Omschrijving

In de 2 voorbeelden wordt het NL GOV profile for CloudEvents niet altijd toegepast zoals in het profiel is beschreven via MUST of SHOULD. Dat is wel wenselijk om:
- het inzicht te vergroten in wat gebruik van het profiel aan meerwaarde heeft 
- duidelijk te maken dat (verdere) standaardisatie wenselijk is voor _de inhoud_ van bepaalde attributen 
- het NL GOV profiel via dit soort voorbeelden en toepassingen te kunnen verbeteren.

Voorbeeld in informatierijk bericht het attribuut "type"  "nl.forumstandaardisatie.open-standaarden.terugmelding".
NL GOV profile:
- In descending order of preference one SHOULD use the name of a data source (for example: 'nl.brp.persoon-verhuisd), domain (for example: nl.natuurlijke-personen.persoon-verhuisd); for domain designation plural MUST be used, law or rule (for example: nl.amsterdam.erfpacht.overdracht).
- Names of organizations SHOULD NOT be used (because they are not durable)
- Sterke voorkeur voor formulering van type in voltooid verleden tijd (beter in profiel te omschrijven!)
- Set gegevens over registratie en melder zijn geen metadata voor bijv. routering of filtering van het event en horen hier dus niet

### Naam

Ad Gerrits

### Email

ad.gerrits@vng.nl

### Organisatie

VNG

**Comment by BasKooij** [comment]
Zie [commit](https://github.com/Logius-standaarden/Terugmelding/commit/fb6e744dd787d94ad16b0c6d9af07c2053f900a3).

Ik heb de inhoud over melding en melder verwijderd uit data-arm en naar het data-element verplaatst voor datarijk. Verder moet dit gezien worden als basis voor discussie over terugmelden. Niet zozeer als een mogelijke specificatie voor een BRP notificatie. Mocht het zo zijn dat er daadwerkelijk behoefte is aan een standaard/specificatie (en in welke vorm) dan werken we dit uiteraard verder uit.

**Comment by sanderke** [comment]
In het Technisch Overleg Terugmelden van 6 juni 2024 is besloten te richten op een minimaal terugmeldbericht en daarmee het CloudEventsformaat uit het ontwerp te halen:
- #7

**Comment by edwinwisse** [comment]
Zie [issue 8](https://github.com/Logius-standaarden/Terugmelding/pull/8/files)
